name: Terraform Lint and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Lint and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Terraform Init (kafka-cluster)
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster

      - name: Terraform Validate (kafka-cluster)
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster

      - name: TFLint (kafka-cluster)
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster
        continue-on-error: true

      - name: TFSec (kafka-cluster)
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster
        continue-on-error: true

      - name: Terraform Init (elasticsearch-fluentd-kibana-cluster)
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster

      - name: Terraform Validate (elasticsearch-fluentd-kibana-cluster)
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster

      - name: TFLint (elasticsearch-fluentd-kibana-cluster)
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster
        continue-on-error: true

      - name: TFSec (elasticsearch-fluentd-kibana-cluster)
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster
        continue-on-error: true

      - name: Terraform Init (prometheus-grafana-cluster)
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster

      - name: Terraform Validate (prometheus-grafana-cluster)
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster

      - name: TFLint (prometheus-grafana-cluster)
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster
        continue-on-error: true

      - name: TFSec (prometheus-grafana-cluster)
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster
        continue-on-error: true

      - name: Terraform Init (redis-cluster)
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/redis-cluster

      - name: Terraform Validate (redis-cluster)
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/redis-cluster

      - name: TFLint (redis-cluster)
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/redis-cluster
        continue-on-error: true

      - name: TFSec (redis-cluster)
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/redis-cluster
        continue-on-error: true

      - name: Terraform Init (vectordb-cluster)
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster

      - name: Terraform Validate (vectordb-cluster)
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster

      - name: TFLint (vectordb-cluster)
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster
        continue-on-error: true

      - name: TFSec (vectordb-cluster)
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster
        continue-on-error: true
        
      - name: Terraform Init (aws-security-group)
        run: terraform init
        working-directory: ${{ github.workspace }}/infrastructure/aws-security-group

      - name: Terraform Validate (aws-security-group)
        run: terraform validate
        working-directory: ${{ github.workspace }}/infrastructure/aws-security-group

      - name: TFLint (aws-security-group)
        run: tflint
        working-directory: ${{ github.workspace }}/infrastructure/aws-security-group
        continue-on-error: true

      - name: TFSec (aws-security-group)
        run: tfsec
        working-directory: ${{ github.workspace }}/infrastructure/aws-security-group
        continue-on-error: true

      - name: Terraform Init (aws-iam-policy-s3)
        run: terraform init
        working-directory: ${{ github.workspace }}/infrastructure/aws-iam-policy-s3

      - name: Terraform Validate (aws-iam-policy-s3)
        run: terraform validate
        working-directory: ${{ github.workspace }}/infrastructure/aws-iam-policy-s3

      - name: TFLint (aws-iam-policy-s3)
        run: tflint
        working-directory: ${{ github.workspace }}/infrastructure/aws-iam-policy-s3
        continue-on-error: true

      - name: TFSec (aws-iam-policy-s3)
        run: tfsec
        working-directory: ${{ github.workspace }}/infrastructure/aws-iam-policy-s3
        continue-on-error: true

      - name: Terraform Init (aws-asg-ec2)
        run: terraform init
        working-directory: ${{ github.workspace }}/infrastructure/aws-asg-ec2

      - name: Terraform Validate (aws-asg-ec2)
        run: terraform validate
        working-directory: ${{ github.workspace }}/infrastructure/aws-asg-ec2

      - name: TFLint (aws-asg-ec2)
        run: tflint
        working-directory: ${{ github.workspace }}/infrastructure/aws-asg-ec2
        continue-on-error: true

      - name: TFSec (aws-asg-ec2)
        run: tfsec
        working-directory: ${{ github.workspace }}/infrastructure/aws-asg-ec2
        continue-on-error: true