name: Terraform Lint and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Lint and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster

      - name: TFLint
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster
        continue-on-error: true

      - name: TFSec
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/kafka-cluster
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster

      - name: TFLint
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster
        continue-on-error: true

      - name: TFSec
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/elasticsearch-fluentd-kibana-cluster
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster

      - name: TFLint
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster
        continue-on-error: true

      - name: TFSec
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/prometheus-grafana-cluster
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/redis-cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/redis-cluster

      - name: TFLint
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/redis-cluster
        continue-on-error: true

      - name: TFSec
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/redis-cluster
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster

      - name: TFLint
        run: tflint
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster
        continue-on-error: true

      - name: TFSec
        run: tfsec
        working-directory: ${{ github.workspace }}/configuration/vectordb-cluster
        continue-on-error: true